# Generated by Django 4.2.7 on 2023-11-30 18:19

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('url_imagem', models.ImageField(null=True, upload_to=core.models.user_image_field)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('digito', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chavePix', models.CharField(max_length=100, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetenteNome', models.CharField(max_length=100)),
                ('destinatarioNome', models.CharField(max_length=100)),
                ('chavePix', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('p', 'PIX'), ('t', 'Transferência'), ('d', 'Depósito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, default='p', max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='core.conta')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('d', 'Debito'), ('c', 'Credito'), ('b', 'Crebito')], default='b', max_length=1)),
                ('numero', models.CharField(default='', max_length=20, unique=True)),
                ('bandeira', models.CharField(default='G', max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
        ),
    ]
