# Generated by Django 4.2.7 on 2023-12-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
    ]
