# Generated by Django 4.2.7 on 2023-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('p', 'p'), ('t', 't'), ('d', 'd')], max_length=1),
        ),
    ]
