# Generated by Django 4.2.7 on 2023-12-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo',
        ),
    ]
