# Generated by Django 4.2.7 on 2023-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=11, unique=True)),
                ('ruaResidencia', models.CharField(max_length=255)),
                ('numeroResidencia', models.CharField(max_length=255)),
                ('bairroResidencia', models.CharField(max_length=255)),
                ('cepResidencia', models.IntegerField()),
                ('estadoResidencia', models.CharField(max_length=255)),
                ('cidadeResidencia', models.CharField(max_length=255)),
            ],
        ),
    ]
