# Generated by Django 4.2.7 on 2023-11-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
