# Generated by Django 4.2.7 on 2023-11-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_cpf_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nascimento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
