# Generated by Django 4.2.7 on 2023-11-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetenteNome', models.CharField(max_length=100)),
                ('destinatarioNome', models.CharField(max_length=100)),
                ('chavePix', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('p', 'PIX'), ('t', 'Transferência'), ('d', 'Depósito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, default='p', max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='api.conta')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='api.conta')),
            ],
        ),
    ]
