# Generated by Django 4.2.7 on 2023-12-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_movimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='remetente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
